## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: run my test
  run: 'make test'
  run_on_init: true
  change:
    - '**/*.vim'
    - '**/*.lua'

- name: run my linter
  run: 'make lint'
  run_on_init: true
  change:
    - '**/*.vim'
    - '**/*.lua'

- name: generate helptags
  run: 'make helptags'
  run_on_init: true
  change:
    - '**/*.txt'
    - '**/*.vim'
    - '**/*.lua'

- name: git stage changed files
  run:
    - git add {{relative_filepath}}
  change:
    - 'doc/tags'
    - '**/*.txt'
    - '**/*.sh'
    - '**/*.nix'
    - '**/*.md'
    - '**/*.vim'
    - '**/*.lua'
